=== sakashushu/HouseholdAccounts/webapps/WEB-INF/dtd/blogic-io.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- ========== Elements ==================== -->

<!-- top level element -->
<!ELEMENT blogic-io     (action*)>

<!-- action -->
<!ELEMENT action        (blogic-params?,blogic-result?)>
<!ATTLIST action        path            CDATA #REQUIRED>

<!-- blogic-params -->
<!ELEMENT blogic-params  (set-property*)>
<!ATTLIST blogic-params bean-name       CDATA #IMPLIED>

<!-- blogic-result -->
<!ELEMENT blogic-result  (set-property*)>

<!-- set-property -->
<!ELEMENT set-property  EMPTY>
<!ATTLIST set-property  property        CDATA          #REQUIRED>
<!ATTLIST set-property  blogic-property CDATA          #IMPLIED>
<!ATTLIST set-property  source          CDATA          #IMPLIED>
<!ATTLIST set-property  dest            CDATA          #IMPLIED>

=== sakashushu/HouseholdAccounts/webapps/WEB-INF/xml/blogic-io-sample.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE blogic-io PUBLIC "-//NTTDATA//DTD TERASOLUNA for Spring blogic-io 1.0//JA"
                           "dtd/blogic-io.dtd">
<!-- ビジネスロジック入出力定義 -->
<blogic-io>
	<action path="/BLogicSample">
		<blogic-params bean-name="blogic.io.BLogicSampleDto">
			<set-property property="last_name" blogic-property="last_name" source="form"></set-property>
			<set-property property="first_name" blogic-property="first_name" source="form"></set-property>
		</blogic-params>
		<blogic-result>
			<set-property property="USER_VALUE_OBJECT" blogic-property="uvo" dest="session"></set-property>
			<set-property property="last_name" blogic-property="last_name" dest="request"></set-property>
			<set-property property="first_name" blogic-property="first_name" dest="request"></set-property>
		</blogic-result>
	</action>
</blogic-io>

=== sakashushu/HouseholdAccounts/webapps/WEB-INF/blogic-io.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE blogic-io PUBLIC "-//NTTDATA//DTD TERASOLUNA for Spring blogic-io 1.0//JA"
                           "dtd/blogic-io.dtd">
<!-- ビジネスロジック入出力定義 -->
<blogic-io>
<!--
	<action path="/logon">
		<blogic-params>
			<set-property property="companyId" blogic-property="companyId" source="request" />
			<set-property property="userId" blogic-property="userId" source="form" />
			<set-property property="password" blogic-property="password" source="form" />
			<set-property property="companyCodeMst" blogic-property="comCodeMst" source="application" />
		</blogic-params>
		<blogic-result>
			<set-property property="longName" blogic-property="longName" dest="session" />
		</blogic-result>
	</action>
-->

	<action path="/DBSample">
		<blogic-params bean-name="blogic.io.DBSampleInput">
			<set-property property="search_kbn" blogic-property="search_kbn" source="form"/>
			<set-property property="search_condition" blogic-property="search_condition" source="form"/>
		</blogic-params>
		<blogic-result>
			<set-property property="search_result" blogic-property="search_result" dest="request"/>
			<set-property property="hit_number" blogic-property="hit_number" dest="request"/>
		</blogic-result>
	</action>

	<action path="/HhaDetail">
		<blogic-params bean-name="hha.blogic.io.HHA_DetailInput">
			<set-property property="year_fr" blogic-property="year_fr" source="form"/>
			<set-property property="month_fr" blogic-property="month_fr" source="form"/>
			<set-property property="year_to" blogic-property="year_to" source="form"/>
			<set-property property="month_to" blogic-property="month_to" source="form"/>
		</blogic-params>
		<blogic-result>
			<set-property property="detail_rslt" blogic-property="detail_rslt" dest="request"/>
			<set-property property="strSelFlg" blogic-property="strSelFlg" dest="request"/>
		</blogic-result>
	</action>

</blogic-io>
